export class ScheduleTB
{
      id:number=0;
      airlineId:number=0;
      flightNum:string='';
      fromPlace:string='';
      toPlace:string='';
      startDate:string='';
      startTime:string='';
      endDate:string='';
      endTime:string='';
      schDays:string='';
      instrumentType:string='';
      bclassSeat:string='';
      nbclassSeat:string='';
      price:string='';
      noOfRows:string='';
      mealPlan:string='';
      status:string='';
}